server:
  port: 8090

spring:
  application:
    name: spring-nacos

  cloud:
    nacos:
      discovery:
        cluster-name: test
        server-addr: localhost:8848
        metadata:
          version: 1.0.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.232.56:3306/nacos-config?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 318412mmpb

