server:
  port: 8085

spring:
  profiles:
    active: dev

  application:
    name: consumer
  rabbitmq:
    host: 127.0.0.1
    username: guest`
    password: guest
    port: 5672
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: auto
