
server:
  port: 8088
spring:
  application:
    name: produce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.110.232:3306/zjgrid_base_data?serverTimezone=GMT%2B8&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&rewriteBatchedStatements=true
    username: basedata
    password: basedata
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      direct:
        acknowledge-mode: manual
