server:
  port: 8999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: 318412mmpb
    type: com.alibaba.druid.pool.DruidDataSource
